{
 "title": "KeyFob System Performance Metrics",
 "description": "Visualizations of the performance of the KeyFob system verses KPIs",
 "time": { "from": "2020-12-07T00:00:00.000Z", "to": "2025-05-26T00:00:00.000Z" },
 "panels": [
  {
   "title": "Valid Forbids - Historical",
   "type": "timeseries",
   "description": "Assigned Keyfobs denied access to Tennis Court or Pool during open periods.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with forbids as\n(\n\tselect distinct fob_id, door,  EXTRACT(week from vk.swipe_time) as week_value, EXTRACT(year from vk.swipe_time) as year_value\n\tfrom door_controller.v_keyswipes vk\n\twhere vk.status = 'Forbid'\n\tand EXTRACT(hour from vk.swipe_time)>6 and EXTRACT(hour from vk.swipe_time) <22\n)\nselect count(*), TO_DATE(year_value::text || week_value::text, 'IYYYIW')\n--from door_controller.v_keyswipes vk\nfrom forbids f\ninner join key_fobs.keyfobs k on\nk.fob_id = f.fob_id\ninner join door_controller.door d\non d.door_no = f.door\nwhere d.door_desc not like '%Club%'\nand f.fob_id in (select fob_id from key_fobs.v_2025_homeowner_fob_list)\ngroup by week_value, year_value\norder by year_value desc, week_value desc;"
    }
   ]
  },
  {
   "title": "Current Week Forbids",
   "type": "gauge",
   "description": "Number of Assigned KeyFobs that were forbid access to Tennis Courts or Pool in the current week.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH forbids AS (\n    SELECT DISTINCT\n        fob_id,\n        door,\n        EXTRACT(week FROM vk.swipe_time) AS week_value,\n        EXTRACT(year FROM vk.swipe_time) AS year_value\n    FROM\n        door_controller.v_keyswipes vk\n    WHERE\n        vk.status = 'Forbid'\n        AND EXTRACT(hour FROM vk.swipe_time) > 6\n        AND EXTRACT(hour FROM vk.swipe_time) < 22\n),\ncurrent_forbids_summary AS (\n    SELECT\n        COALESCE(COUNT(*), 0) AS forbid_count,\n        TO_DATE(year_value::text || LPAD(week_value::text, 2, '0'), 'IYYYIW') AS the_date\n    FROM\n        forbids f\n    INNER JOIN\n        key_fobs.keyfobs k ON k.fob_id = f.fob_id\n    INNER JOIN\n        door_controller.door d ON d.door_no = f.door\n    WHERE\n        d.door_desc NOT LIKE '%Club%'\n        AND f.fob_id IN (SELECT fob_id FROM key_fobs.v_2025_homeowner_fob_list)\n    GROUP BY\n        week_value,\n        year_value\n),\nthis_week_calc AS (\n    -- Calculate the current week's Monday date based on ISO week\n    SELECT\n        TO_DATE(EXTRACT(year FROM CURRENT_DATE)::text || LPAD(EXTRACT(week FROM CURRENT_DATE)::text, 2, '0'), 'IYYYIW') AS current_week_monday\n)\nSELECT\n    COALESCE(cfs.forbid_count, 0) AS final_forbid_count\nFROM\n    this_week_calc twc\nLEFT JOIN\n    current_forbids_summary cfs ON twc.current_week_monday = cfs.the_date;\n"
    }
   ]
  },
  {
   "title": "Historical Unauthorized Accesses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "with forbids as\n(\n\tselect distinct fob_id, door,  EXTRACT(week from vk.swipe_time) as week_value, EXTRACT(year from vk.swipe_time) as year_value\n\tfrom door_controller.v_keyswipes vk\n\twhere vk.status = 'Allow'\n\tand EXTRACT(hour from vk.swipe_time)>6 and EXTRACT(hour from vk.swipe_time) <22\n)\nselect count(*), TO_DATE(year_value::text || week_value::text, 'IYYYIW')\n--from door_controller.v_keyswipes vk\nfrom forbids f\ninner join key_fobs.keyfobs k on\nk.fob_id = f.fob_id\ninner join door_controller.door d\non d.door_no = f.door\nwhere d.door_desc not like '%Club%'\nand f.fob_id not in (select fob_id from key_fobs.v_2025_homeowner_fob_list)\ngroup by week_value, year_value\norder by year_value desc, week_value desc;"
    }
   ]
  },
  {
   "title": "Unauthroized Access - Current Week",
   "type": "gauge",
   "description": "Count of Unassigned KeyfobID being used to access Pool or Tennis courts during operating hours during the current week.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH forbids AS (\n    SELECT DISTINCT\n        fob_id,\n        door,\n        EXTRACT(week FROM vk.swipe_time) AS week_value,\n        EXTRACT(year FROM vk.swipe_time) AS year_value\n    FROM\n        door_controller.v_keyswipes vk\n    WHERE\n        vk.status = 'Allow'\n        AND EXTRACT(hour FROM vk.swipe_time) > 6\n        AND EXTRACT(hour FROM vk.swipe_time) < 22\n),\ncurrent_forbids_summary AS (\n    SELECT\n        COALESCE(COUNT(*), 0) AS forbid_count,\n        TO_DATE(year_value::text || LPAD(week_value::text, 2, '0'), 'IYYYIW') AS the_date\n    FROM\n        forbids f\n    INNER JOIN\n        key_fobs.keyfobs k ON k.fob_id = f.fob_id\n    INNER JOIN\n        door_controller.door d ON d.door_no = f.door\n    WHERE\n        d.door_desc NOT LIKE '%Club%'\n        AND f.fob_id NOT IN (SELECT fob_id FROM key_fobs.v_2025_homeowner_fob_list)\n    GROUP BY\n        week_value,\n        year_value\n),\nthis_week_calc AS (\n    -- Calculate the current week's Monday date based on ISO week\n    SELECT\n        TO_DATE(EXTRACT(year FROM CURRENT_DATE)::text || LPAD(EXTRACT(week FROM CURRENT_DATE)::text, 2, '0'), 'IYYYIW') AS current_week_monday\n)\nSELECT\n    COALESCE(cfs.forbid_count, 0) AS final_forbid_count\nFROM\n    this_week_calc twc\nLEFT JOIN\n    current_forbids_summary cfs ON twc.current_week_monday = cfs.the_date;\n"
    }
   ]
  }
 ]
}