{
 "title": "Wentworth Amenites",
 "time": { "from": "2020-10-27T00:00:00.000Z", "to": "2025-05-24T00:00:00.000Z" },
 "panels": [
  {
   "title": "Tennis Court Usage by Property Address",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT swipe_percent, prop_address FROM door_controller.v_tannis_court_usage LIMIT 50 "
    }
   ]
  },
  {
   "title": "Pool Usage by Property",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT prop_address, swipe_percent FROM door_controller.v_pool_usage LIMIT 50 "
    }
   ]
  },
  {
   "title": "Tennis Court Daily Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT record_date, record_count FROM door_controller.v_tenniscourt_daily_usage"
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT record_count, $__time(record_date) FROM door_controller.v_pool_daily_usage"
    }
   ]
  }
 ]
}